# Generated by Django 3.1.2 on 2020-10-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201006_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='NONE', max_length=2083),
        ),
    ]
